# -*- coding: utf-8 -*-
"""data_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUDGNAvQIcyFgZWzyK6r5o7IVP4BpEW_
"""



from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/drive/MyDrive/Brain_tumor/src/data_loader.py
# 
#

!python /content/drive/MyDrive/Brain_tumor/src/preprocessing.py

import numpy as np
from sklearn.model_selection import train_test_split
import os

def load_data():

    file_path = "brain_tumor_data.npz"

    if not os.path.exists(file_path):
        print("ERROR: Run Day 2 preprocessing first")
        return None

    data = np.load(file_path)

    X = data["X"]
    y = data["y"]

    print("Data loaded:", X.shape)

    return X, y

def split_data(X, y):

    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y,
        test_size=0.3,
        random_state=42,
        stratify=y
    )


    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=0.5,
        random_state=42,
        stratify=y_temp
    )

    return X_train, y_train, X_val, y_val, X_test, y_test

def save_data(X_train, y_train, X_val, y_val, X_test, y_test):

    np.savez_compressed(
        "brain_tumor_splits.npz",
        X_train=X_train,
        y_train=y_train,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test
    )

    print("Splits saved successfully!")

def main():

    data = load_data()

    if data is None:
        return

    X, y = data

    X_train, y_train, X_val, y_val, X_test, y_test = split_data(X, y)

    print("Train:", X_train.shape)
    print("Val:", X_val.shape)
    print("Test:", X_test.shape)

    save_data(X_train, y_train, X_val, y_val, X_test, y_test)

if __name__ == "__main__":
    main()